name: Run unit tests
description: Action runs `xcodebuild test` on xcode 16.x

inputs:
  codecov-token:
    description: Codecov token
    type: string
    required: false

runs:
  using: composite
  steps:
    - name: Set up Xcode 16
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 16.4.0

    - name: Run unit tests
      run: >
        set -o pipefail &&
        xcodebuild -skipPackagePluginValidation -scheme RoktUXHelper -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.4' -enableCodeCoverage YES -derivedDataPath DerivedData clean build test
        | xcbeautify --renderer github-actions
      shell: bash

    - name: Install xcresultparser
      if: ${{ inputs.codecov-token != '' }}
      run: brew install xcresultparser
      shell: bash

    - name: Process coverage report
      if: ${{ inputs.codecov-token != '' }}
      shell: bash
      run: |
        mkdir -p artifacts
        xcresultparser --output-format cobertura "$(find DerivedData/Logs/Test -name '*.xcresult' | head -n 1)" --project-root "$(pwd)" > "artifacts/coverage.xml"

    - name: Upload coverage report
      if: ${{ inputs.codecov-token != '' }}
      uses: codecov/codecov-action@v5
      with:
        token: ${{ inputs.codecov-token }}
        files: ./artifacts/coverage.xml
        flags: unittests
