coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - Example/**
  - Tests/**
  - .github/**
  - DerivedData/**
  - .swiftpm/**
  - "*.md"
  - "*.yml"
  - "*.yaml"
  - "*.lock"
  - Package.resolved
  - VERSION
  - LICENSE.md
  - SECURITY.md
  - MIGRATING.md
  - README.md
  - CHANGELOG.md
