# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Runs all the tests"
  lane :test do
    run_swift_package_tests
  end

  desc "Run unit tests"
  lane :run_swift_package_tests do
    sh(" \
      cd .. \
      && xcodebuild -resolvePackageDependencies -scheme RoktUXHelper -clonedSourcePackagesDirPath . \
      && xcodebuild -skipPackagePluginValidation -scheme RoktUXHelper test -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
      ")
  end

end
