# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Run tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

permissions:
  contents: "read"
  id-token: "write"

jobs:
  unit-test:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Resolve Packages
        run: swift package resolve --verbose

      - name: Install xcbeautify
        run: |
          brew list xcbeautify || brew install xcbeautify

      - name: Run unit tests
        uses: ./.github/composite_actions/run_xcodebuild_tests
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  pr-notify:
    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.draft == false
    needs: [unit-test]
    name: Notify GChat
    uses: ROKT/rokt-workflows/.github/workflows/oss_pr_opened_notification.yml@main
    secrets:
      gchat_webhook: ${{ secrets.GCHAT_PRS_MOBILE_INTEGRATION_CHANNEL_WEBHOOK }}
