# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Run tests

permissions:
  contents: read
  pull-requests: read
  id-token: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trunk-check:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Trunk Check
        uses: trunk-io/trunk-action@75699af9e26881e564e9d832ef7dc3af25ec031b # v1.2.4
        with:
          check-mode: all

  unit-test:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Resolve Packages
        run: swift package resolve --verbose

      - name: Install xcbeautify
        run: |
          brew list xcbeautify || brew install xcbeautify

      - name: Run unit tests
        uses: ./.github/composite_actions/run_xcodebuild_tests
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  pr-notify:
    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.draft == false
    needs: [trunk-check, unit-test]
    name: Notify GChat
    uses: ROKT/rokt-workflows/.github/workflows/oss_pr_opened_notification.yml@main
    secrets:
      gchat_webhook: ${{ secrets.GCHAT_PRS_MOBILE_INTEGRATION_CHANNEL_WEBHOOK }}
