# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: pull request

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  unit-test:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Resolve Packages
        run: swift package resolve --verbose

      - name: Install xcbeautify
        run: |
          brew list xcbeautify || brew install xcbeautify

      - name: Run unit tests
        uses: ./.github/composite_actions/run_xcodebuild_tests
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
